// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymrxnqbupvapieorpyxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltcnhucWJ1cHZhcGllb3JweXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTU0NDEsImV4cCI6MjA3NDI5MTQ0MX0.iky5ghWI2kj0mg5TV_fQVI6QNsUlUpLUk-J9inzM2Dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});